# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Question.create(p_type: 0, q_type: "申論", o_comment: "申論時間六分鐘，請候選人開始。", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "市民的照護", option_a_key: 40, option_b:"居住與環境", option_b_key: 41, option_c:"市政的行政與法務", option_c_key: 42, option_d: "食品安全", option_d_key: 43 )
Question.create(p_type: 0, q_type: "交叉詰問", o_comment: "候選人，選舉不是算數，拿著收支表在鏡頭前嗆聲更不是監督市政！請問面對市民福利與生活，你有沒有真正的市政方向！", m_comment: "我覺得是這樣子啦！這個問題齁，要從_ _方面解決....", option_a: "市民的照護", option_a_key: 40, option_b:"居住與環境", option_b_key: 41, option_c:"市政的行政與法務", option_c_key: 42, option_d: "食品安全", option_d_key: 43 )
Question.create(p_type: 0, q_type: "結論", o_comment: "結論時間六分鐘，請候選人開始。", m_comment: "最後的結論，我想再次強調.....", option_a: "市民的照護", option_a_key: 40, option_b:"居住與環境", option_b_key: 41, option_c:"市政的行政與法務", option_c_key: 42, option_d: "食品安全", option_d_key: 43 )
Question.create(p_type: 3, q_type: "申論", o_comment: "申論時間六分鐘，請候選人開始。", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "國民義務教育", option_a_key: 44, option_b:"地方體育發展", option_b_key: 45, option_c:"地方文化保存", option_c_key: 46, option_d: "完善文教相關法規", option_d_key: 57 )
Question.create(p_type: 3, q_type: "交叉詰問", o_comment: "我想請教候選人，面臨國民競爭力下滑，請問在文教發展上有沒有什麼看法？", m_comment: "我覺得是這樣子啦！這個問題齁，要從_ _方面解決....", option_a: "國民義務教育", option_a_key: 44, option_b:"地方體育發展", option_b_key: 45, option_c:"地方文化保存", option_c_key: 46, option_d: "完善文教相關法規", option_d_key: 57 )
Question.create(p_type: 3, q_type: "結論", o_comment: "結論時間六分鐘，請候選人開始。", m_comment: "最後的結論，我想再次強調.....", option_a: "國民義務教育", option_a_key: 44, option_b:"地方體育發展", option_b_key: 45, option_c:"地方文化保存", option_c_key: 46, option_d: "完善文教相關法規", option_d_key: 57 )
Question.create(p_type: 4, q_type: "申論", o_comment: "申論時間六分鐘，請候選人開始。", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "青壯年人口的失業率", option_a_key: 53, option_b:"青年創新", option_b_key: 54, option_c:"青年參政", option_c_key: 58, option_d: "年輕人目前買房的困境", option_d_key: 61 )
Question.create(p_type: 4, q_type: "交叉詰問", o_comment: "你身為青年參政代表，應該更了解現在年輕人的困境。你認為現在年輕人面對最沈痛的問題是什麼？要怎麼解決？", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "青壯年人口的失業率", option_a_key: 53, option_b:"青年創新", option_b_key: 54, option_c:"青年參政", option_c_key: 58, option_d: "年輕人目前買房的困境", option_d_key: 61 )
Question.create(p_type: 4, q_type: "結論", o_comment: "結論時間六分鐘，請候選人開始。", m_comment: "最後的結論，我想再次強調.....", option_a: "青壯年人口的失業率", option_a_key: 53, option_b:"青年創新", option_b_key: 54, option_c:"青年參政", option_c_key: 58, option_d: "年輕人目前買房的困境", option_d_key: 61 )
Question.create(p_type: 1, q_type: "申論", o_comment: "申論時間六分鐘，請候選人開始。", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "基礎交通建設", option_a_key: 55, option_b:"用路人應有的權利", option_b_key: 48, option_c:"現行交通制度", option_c_key: 47, option_d: "改善交通規劃", option_d_key: 63 )
Question.create(p_type: 1, q_type: "交叉詰問", o_comment: "交通是城市的血脈，更需要經驗的累積來解決。首次參選的你，有足夠的經驗和政策解決交通問題嗎？", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "基礎交通建設", option_a_key: 55, option_b:"用路人應有的權利", option_b_key: 48, option_c:"現行交通制度", option_c_key: 47, option_d: "改善交通規劃", option_d_key: 63 )
Question.create(p_type: 1, q_type: "結論", o_comment: "結論時間六分鐘，請候選人開始。", m_comment: "最後的結論，我想再次強調.....", option_a: "基礎交通建設", option_a_key: 55, option_b:"用路人應有的權利", option_b_key: 48, option_c:"現行交通制度", option_c_key: 47, option_d: "改善交通規劃", option_d_key: 63 )
Question.create(p_type: 2, q_type: "申論", o_comment: "申論時間六分鐘，請候選人開始。", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "城市的願景", option_a_key: 51, option_b:"地方人才外流的議題", option_b_key: 52, option_c:"勞工應該要有的照護", option_c_key: 56, option_d: "觀光發展", option_d_key: 64 )
Question.create(p_type: 2, q_type: "交叉詰問", o_comment: "每個人都在說拚經濟！拼到最後也都是空頭支票，對於這種惡習，你要怎麼避免？", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "城市的願景", option_a_key: 51, option_b:"地方人才外流的議題", option_b_key: 52, option_c:"勞工應該要有的照護", option_c_key: 56, option_d: "觀光發展", option_d_key: 64 )
Question.create(p_type: 2, q_type: "結論", o_comment: "結論時間六分鐘，請候選人開始。", m_comment: "最後的結論，我想再次強調.....", option_a: "城市的願景", option_a_key: 51, option_b:"地方人才外流的議題", option_b_key: 52, option_c:"勞工應該要有的照護", option_c_key: 56, option_d: "觀光發展", option_d_key: 64 )
Question.create(p_type: 5, q_type: "申論", o_comment: "申論時間六分鐘，請候選人開始。", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "公民在乎的意識形態", option_a_key: 59, option_b:"公民參政", option_b_key: 60, option_c:"性別平權教育", option_c_key: 65, option_d: "移民議題", option_d_key: 66 )
Question.create(p_type: 5, q_type: "交叉詰問", o_comment: "政治是從公民參與開始，你身為素人參政，在這部分有特別的見解嗎？", m_comment: "謝謝主持人，今天的辯論我想從_ _開始.....", option_a: "公民在乎的意識形態", option_a_key: 59, option_b:"公民參政", option_b_key: 60, option_c:"性別平權教育", option_c_key: 65, option_d: "移民議題", option_d_key: 66 )
Question.create(p_type: 5, q_type: "結論", o_comment: "結論時間六分鐘，請候選人開始。", m_comment: "最後的結論，我想再次強調.....", option_a: "公民在乎的意識形態", option_a_key: 59, option_b:"公民參政", option_b_key: 60, option_c:"性別平權教育", option_c_key: 65, option_d: "移民議題", option_d_key: 66 )